export const PurchaseFormItems = [
    {
        step: 1,
        label: 'Full Name',
        placeholder: 'Full Name',
        name: 'fullName',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 1,
        label: 'Email Adress',
        placeholder: 'Email',
        name: 'email',
        type: 'email',
        isLong: true,
        regex: '',
    },
    {
        step: 2,
        label: 'Address',
        placeholder: 'Street, City',
        name: 'address',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 2,
        label: 'Country',
        placeholder: 'Country',
        name: 'country',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 3,
        label: `Cardholder's Name`,
        placeholder: 'Full Name',
        name: 'cardName',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 3,
        label: 'Card Number',
        placeholder: '---- ---- ---- ----',
        name: 'cardNumber',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 4,
        label: 'Expiry Date',
        placeholder: 'MM/YY',
        name: 'cardDate',
        type: 'text',
        isLong: true,
        regex: '',
    },
    {
        step: 4,
        label: 'CVV',
        placeholder: 'CVV',
        name: 'cardCvv',
        type: 'text',
        isLong: true,
        regex: '',
    },
]
