export default function Features() {
  return (
    <section>
      <div>
        <div>
          <div>
            Icon
          </div>
          <h3>Title</h3>
          <p>description</p>
        </div>
        <div>
          <div>
            Icon
          </div>
          <h3>Title</h3>
          <p>description</p>
        </div>
        <div>
          <div>
            Icon
          </div>
          <h3>Title</h3>
          <p>description</p>
        </div>
      </div>
    </section>
  )
}